Verify commit signoff GHA
canonical/kernel-docs pull request #24
Opened 2024-11-26 02:46 UTC by AnneCYH

2024-11-26 16:12 UTC, benjamin051000 requested changes

2024-11-27 05:48 UTC, AnneCYH commented on .github/workflows/verify-commit-signoff.yml
> +  push:
We can change that for sure. Less resource intensive this way also.

2024-11-27 05:59 UTC, AnneCYH commented on .github/workflows/verify-commit-signoff.yml
> +  push:
hey @benjamin051000 where is this action defined?
https://kernel.ubuntu.com/gitea/kernel/kteam-tools/src/commit/6b7f4e2c20902939d1c31461ed414290240862fe/.gitea/workflows/pr_check.yaml#L89

the verify-signoff workflow here doesn't seem to be robust enough when i squash commits; it's grabbing the wrong commit ID to check

2024-11-27 06:44 UTC, AnneCYH commented on .github/workflows/verify-commit-signoff.yml
> +  push:
it should be working as expected now.
tested with a few squashes and pushes.

Thanks.

2024-12-02 12:06 UTC, benjamin051000 commented on .github/workflows/verify-commit-signoff.yml
> +  push:
Hey @AnneCYH, I've been on PTO for the past 5 days, lol. The action is defined here: https://kernel.ubuntu.com/gitea/actions/tnt-sign-off-check. I'm not sure if you found that before.

2024-12-02 12:08 UTC, benjamin051000 approved these changes
Looks like this is working as intended, LGTM.

2024-12-02 12:08 UTC, benjamin051000 commented on .github/workflows/verify-commit-signoff.yml
> +  push:
This looks better to me. Thanks for that update.

2024-12-02 12:50 UTC, merged